// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services;

/// <summary>
/// Reads the current user identity from Azure App Service EasyAuth headers.
/// </summary>
public class CurrentUserService : ICurrentUserService
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public CurrentUserService(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public string? GetUserId()
        => _httpContextAccessor.HttpContext?.Request.Headers["X-MS-CLIENT-PRINCIPAL-ID"].FirstOrDefault();

    public string? GetUserEmail()
        => _httpContextAccessor.HttpContext?.Request.Headers["X-MS-CLIENT-PRINCIPAL-NAME"].FirstOrDefault();

    public string? GetDisplayName()
        => GetUserEmail();
}
