// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services.Reflections;

namespace AntarMindAI.Api.Services;

public interface IAiSummaryService
{
    Task<string?> GenerateWeeklySummaryAsync(WeeklyReflection reflection);
}
