// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services;

public record SentimentResult(string Sentiment, double IntensityScore);

public interface ISentimentAnalyzer
{
    SentimentResult Analyze(IReadOnlyList<string> tokens);
}
