// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services;

public record ThoughtAnalysisResult(
    IReadOnlyList<string> Tags,
    string Sentiment,
    double IntensityScore
);

public interface IThoughtAnalysisPipeline
{
    ThoughtAnalysisResult Analyze(string text);
}
