// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services;

/// <summary>
/// Development stub for ICurrentUserService — returns a fixed local dev identity.
/// Only registered in Development and Testing environments.
/// </summary>
public class LocalDevCurrentUserService : ICurrentUserService
{
    public string? GetUserId() => "localdev-user-id";
    public string? GetUserEmail() => "dev@antarmindai.local";
    public string? GetDisplayName() => "Local Dev User";
}
