// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services.Reflections;

namespace AntarMindAI.Api.Services;

/// <summary>Default no-op implementation used when AI summary is disabled.</summary>
public class NullAiSummaryService : IAiSummaryService
{
    public Task<string?> GenerateWeeklySummaryAsync(WeeklyReflection reflection)
        => Task.FromResult<string?>(null);
}
