// Generated by AI on 05/04/2026
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using AntarMindAI.Api.Services.Reflections;

namespace AntarMindAI.Api.Services;

public class OpenAiSummaryService : IAiSummaryService
{
    private readonly string _apiKey;
    private static readonly HttpClient _http = new();

    public OpenAiSummaryService(string apiKey)
    {
        _apiKey = apiKey;
    }

    public async Task<string?> GenerateWeeklySummaryAsync(WeeklyReflection reflection)
    {
        try
        {
            var topCategories = string.Join(", ", reflection.CategoryDistribution.Take(3).Select(c => $"{c.Category} ({c.Percentage}%)"));
            var prompt = $"""
                You are a compassionate mindfulness assistant. Based on the following weekly thought statistics, write a 2-3 sentence supportive summary for the user. Do NOT mention any raw personal content — only use the statistics provided.

                Week: {reflection.WeekStart:MMM d} – {reflection.WeekEnd:MMM d, yyyy}
                Total thoughts logged: {reflection.TotalThoughts}
                Top categories: {topCategories}
                Daily sentiment trend (Positive/Negative/Neutral per day):
                {string.Join("\n", reflection.DailySentimentTrend.Select(d => $"  {d.Day}: +{d.Positive} -{d.Negative} ={d.Neutral}"))}

                Provide a brief, warm, encouraging summary.
                """;

            var payload = new
            {
                model = "gpt-4o-mini",
                messages = new[] { new { role = "user", content = prompt } },
                max_tokens = 150,
                temperature = 0.7
            };

            var request = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/chat/completions");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);
            request.Content = new StringContent(JsonSerializer.Serialize(payload), Encoding.UTF8, "application/json");

            var response = await _http.SendAsync(request);
            response.EnsureSuccessStatusCode();

            var body = await response.Content.ReadAsStringAsync();
            using var doc = JsonDocument.Parse(body);
            return doc.RootElement
                .GetProperty("choices")[0]
                .GetProperty("message")
                .GetProperty("content")
                .GetString();
        }
        catch
        {
            return null;
        }
    }
}
