// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services;

public class ThoughtAnalysisPipeline : IThoughtAnalysisPipeline
{
    private readonly ITextPreprocessor _preprocessor;
    private readonly ITaggingEngine _tagger;
    private readonly ISentimentAnalyzer _sentimentAnalyzer;

    public ThoughtAnalysisPipeline(
        ITextPreprocessor preprocessor,
        ITaggingEngine tagger,
        ISentimentAnalyzer sentimentAnalyzer)
    {
        _preprocessor = preprocessor;
        _tagger = tagger;
        _sentimentAnalyzer = sentimentAnalyzer;
    }

    public ThoughtAnalysisResult Analyze(string text)
    {
        var tokens = _preprocessor.Tokenize(text);
        var tags = _tagger.GetTags(tokens);
        var sentiment = _sentimentAnalyzer.Analyze(tokens);

        return new ThoughtAnalysisResult(tags, sentiment.Sentiment, sentiment.IntensityScore);
    }
}
