// Generated by AI on 05/04/2026
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.Hosting;

namespace AntarMindAI.Tests;

/// <summary>
/// A <see cref="WebApplicationFactory{TEntryPoint}"/> that runs the API in a "Testing"
/// environment so that the EasyAuth handler is active (same as production)
/// rather than the development bypass service.
/// </summary>
public class TestApiFactory : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseEnvironment("Testing");
    }
}
