// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Models;

public class ThoughtEntry
{
    public string Id { get; set; } = string.Empty;
    public string UserId { get; set; } = string.Empty;
    public string Text { get; set; } = string.Empty;
    public DateTimeOffset CreatedAt { get; set; }
}
