// Generated by AI on 05/04/2026
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    // Output to the API project's wwwroot/ui so it's served as static files
    outDir: path.resolve(__dirname, '../src/AntarMindAI.Api/wwwroot/ui'),
    emptyOutDir: true,
  },
  server: {
    // Proxy API calls to the .NET backend during local development
    proxy: {
      '/api': {
        target: 'https://localhost:7100',
        changeOrigin: true,
        secure: false,
      },
    },
  },
})
