// Generated by AI on 05/04/2026
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using AntarMindAI.Api.Repositories;

namespace AntarMindAI.Api.Services.Embeddings;

public class AzureOpenAiEmbeddingService : IEmbeddingService
{
    private readonly IThoughtRepository _repository;
    private readonly HttpClient _httpClient;
    private readonly string _apiKey;
    private readonly string _deploymentUrl;

    public AzureOpenAiEmbeddingService(
        IThoughtRepository repository,
        string apiKey,
        string deploymentUrl)
    {
        _repository = repository;
        _apiKey = apiKey;
        _deploymentUrl = deploymentUrl;
        _httpClient = new HttpClient();
        _httpClient.DefaultRequestHeaders.Add("api-key", _apiKey);
    }

    public async Task<float[]> GetEmbeddingAsync(string text)
    {
        var payload = new { input = text };
        var json = JsonSerializer.Serialize(payload);
        using var content = new StringContent(json, Encoding.UTF8, "application/json");

        var response = await _httpClient.PostAsync(_deploymentUrl, content);
        response.EnsureSuccessStatusCode();

        var responseJson = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(responseJson);
        var dataArray = doc.RootElement.GetProperty("data")[0].GetProperty("embedding");

        return dataArray.EnumerateArray().Select(v => v.GetSingle()).ToArray();
    }

    public async Task<IReadOnlyList<SimilarThought>> FindSimilarAsync(string userId, string thoughtId, int topN = 5)
    {
        var thoughts = await _repository.GetAllByUserAsync(userId);
        var target = thoughts.FirstOrDefault(t => t.Id == thoughtId);

        if (target?.Embedding is null || target.Embedding.Length == 0)
            return [];

        var results = thoughts
            .Where(t => t.Id != thoughtId && t.Embedding is { Length: > 0 })
            .Select(t => new SimilarThought(
                ThoughtId: t.Id,
                Text: t.Text,
                CreatedAt: t.CreatedAt,
                SimilarityScore: CosineSimilarity(target.Embedding, t.Embedding!)))
            .OrderByDescending(s => s.SimilarityScore)
            .Take(topN)
            .ToList();

        return results;
    }

    private static double CosineSimilarity(float[] a, float[] b)
    {
        if (a.Length != b.Length) return 0.0;
        double dot = 0, normA = 0, normB = 0;
        for (int i = 0; i < a.Length; i++)
        {
            dot += a[i] * b[i];
            normA += a[i] * a[i];
            normB += b[i] * b[i];
        }
        var denom = Math.Sqrt(normA) * Math.Sqrt(normB);
        return denom == 0.0 ? 0.0 : dot / denom;
    }
}
