// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services.Embeddings;

public record SimilarThought(string ThoughtId, string Text, DateTimeOffset CreatedAt, double SimilarityScore);

public interface IEmbeddingService
{
    Task<float[]> GetEmbeddingAsync(string text);
    Task<IReadOnlyList<SimilarThought>> FindSimilarAsync(string userId, string thoughtId, int topN = 5);
}
