// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services.Embeddings;

public class NullEmbeddingService : IEmbeddingService
{
    public Task<float[]> GetEmbeddingAsync(string text) => Task.FromResult(Array.Empty<float>());

    public Task<IReadOnlyList<SimilarThought>> FindSimilarAsync(string userId, string thoughtId, int topN = 5) =>
        Task.FromResult<IReadOnlyList<SimilarThought>>([]);
}
