// Generated by AI on 05/04/2026
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

namespace AntarMindAI.Tests.Thoughts;

public class ThoughtSearchTests : IClassFixture<TestApiFactory>
{
    private readonly HttpClient _client;

    public ThoughtSearchTests(TestApiFactory factory)
    {
        _client = factory.CreateClient();
    }

    private async Task SeedAsync(string text)
    {
        var r = await _client.PostAsJsonAsync("/api/thoughts", new { text });
        r.EnsureSuccessStatusCode();
    }

    [Fact]
    public async Task Search_MissingQ_Returns400()
    {
        var response = await _client.GetAsync("/api/thoughts/search");

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
    }

    [Fact]
    public async Task Search_MatchByText_ReturnsResults()
    {
        await SeedAsync("stressed about my trading losses today");

        var response = await _client.GetAsync("/api/thoughts/search?q=trading");
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);
        Assert.True(doc.RootElement.GetProperty("totalCount").GetInt32() >= 1);
    }

    [Fact]
    public async Task Search_NoMatch_ReturnsEmptyNotNotFound()
    {
        var response = await _client.GetAsync("/api/thoughts/search?q=xyznosuchwordinanyentry12345");
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);
        Assert.Equal(0, doc.RootElement.GetProperty("totalCount").GetInt32());
    }
}
