// Generated by AI on 05/04/2026
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export function AppHeader() {
  return (
    <AppBar position="sticky">
      <Toolbar>
        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
          AntarMindAI
        </Typography>
      </Toolbar>
    </AppBar>
  );
}
