// Generated by AI on 05/04/2026
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import CircularProgress from '@mui/material/CircularProgress';
import Typography from '@mui/material/Typography';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { getThoughts } from '../api/thoughts';
import { ThoughtCard } from './ThoughtCard';

const PAGE_SIZE = 20;

export function ThoughtList() {
  const [page, setPage] = useState(1);

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['thoughts', page],
    queryFn: () => getThoughts(page, PAGE_SIZE),
  });

  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
        <CircularProgress />
      </Box>
    );
  }

  if (isError) {
    return <Alert severity="error">{error?.message ?? 'Failed to load thoughts'}</Alert>;
  }

  const thoughts = data?.items ?? [];
  const totalCount = data?.totalCount ?? 0;
  const totalPages = Math.ceil(totalCount / PAGE_SIZE);

  return (
    <Box>
      {thoughts.length === 0 ? (
        <Typography color="text.secondary" align="center" sx={{ py: 4 }}>
          No thoughts yet. Start writing above!
        </Typography>
      ) : (
        thoughts.map((thought) => <ThoughtCard key={thought.id} thought={thought} />)
      )}
      {totalPages > 1 && (
        <Box sx={{ display: 'flex', justifyContent: 'center', gap: 1, mt: 2 }}>
          <Button
            variant="outlined"
            size="small"
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={page <= 1}
          >
            Previous
          </Button>
          <Typography variant="body2" sx={{ alignSelf: 'center' }}>
            Page {page} of {totalPages}
          </Typography>
          <Button
            variant="outlined"
            size="small"
            onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            disabled={page >= totalPages}
          >
            Next
          </Button>
        </Box>
      )}
    </Box>
  );
}
