// Generated by AI on 05/04/2026
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import CircularProgress from '@mui/material/CircularProgress';
import TextField from '@mui/material/TextField';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { createThought } from '../api/thoughts';

export function ThoughtInput() {
  const [text, setText] = useState('');
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: createThought,
    onSuccess: () => {
      setText('');
      queryClient.invalidateQueries({ queryKey: ['thoughts'] });
    },
  });

  const handleSubmit = () => {
    if (text.trim().length === 0) return;
    mutation.mutate({ text: text.trim() });
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, mb: 3 }}>
      <TextField
        label="What's on your mind?"
        multiline
        minRows={3}
        value={text}
        onChange={(e) => setText(e.target.value)}
        inputProps={{ maxLength: 2000 }}
        disabled={mutation.isPending}
        fullWidth
      />
      {mutation.isError && (
        <Alert severity="error">{mutation.error?.message ?? 'Something went wrong'}</Alert>
      )}
      <Box sx={{ display: 'flex', justifyContent: 'flex-end' }}>
        <Button
          variant="contained"
          onClick={handleSubmit}
          disabled={mutation.isPending || text.trim().length === 0}
          startIcon={mutation.isPending ? <CircularProgress size={16} color="inherit" /> : null}
        >
          {mutation.isPending ? 'Saving…' : 'Save Thought'}
        </Button>
      </Box>
    </Box>
  );
}
