// Generated by AI on 05/04/2026
import Typography from '@mui/material/Typography';
import { BarChart } from '@mui/x-charts/BarChart';
import type { HourlyActivityResponse } from '../../api/reflections';

interface Props {
  data: HourlyActivityResponse[];
}

export function ActivityHeatmap({ data }: Props) {
  const hasData = data.some(h => h.thoughtCount > 0);
  if (!hasData) {
    return <Typography variant="body2" color="text.secondary">No activity data this week.</Typography>;
  }

  return (
    <BarChart
      xAxis={[{ scaleType: 'band', data: data.map(h => `${h.hour}h`) }]}
      series={[{ data: data.map(h => h.thoughtCount), label: 'Thoughts', color: '#1976d2' }]}
      height={200}
    />
  );
}
