// Generated by AI on 05/04/2026
import Typography from '@mui/material/Typography';
import { PieChart } from '@mui/x-charts/PieChart';
import type { CategoryCountResponse } from '../../api/reflections';

interface Props {
  data: CategoryCountResponse[];
}

export function CategoryChart({ data }: Props) {
  if (data.length === 0) {
    return <Typography variant="body2" color="text.secondary">No category data this week.</Typography>;
  }

  const series = data.map((c, i) => ({
    id: i,
    value: c.count,
    label: `${c.category} (${c.percentage}%)`,
  }));

  return (
    <PieChart
      series={[{ data: series, highlightScope: { fade: 'global', highlight: 'item' } }]}
      height={260}
    />
  );
}
