// Generated by AI on 05/04/2026
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Chip from '@mui/material/Chip';
import Typography from '@mui/material/Typography';
import type { InsightMessageResponse } from '../../api/reflections';

interface Props {
  insights: InsightMessageResponse[];
}

const categoryColor: Record<string, 'primary' | 'secondary' | 'warning' | 'error' | 'default'> = {
  Frequency: 'primary',
  TimeTrend: 'secondary',
  Repetition: 'warning',
  Trigger: 'error',
};

export function PatternHighlights({ insights }: Props) {
  if (insights.length === 0) {
    return (
      <Typography variant="body2" color="text.secondary">
        No pattern highlights yet.
      </Typography>
    );
  }

  return (
    <Box display="flex" flexDirection="column" gap={1}>
      {insights.slice(0, 3).map((insight, idx) => (
        <Card key={idx} variant="outlined">
          <CardContent sx={{ py: 1.5, '&:last-child': { pb: 1.5 } }}>
            <Box display="flex" alignItems="center" gap={1} flexWrap="wrap">
              <Chip
                label={insight.category}
                size="small"
                color={categoryColor[insight.category] ?? 'default'}
              />
              <Typography variant="body2">{insight.message}</Typography>
            </Box>
          </CardContent>
        </Card>
      ))}
    </Box>
  );
}
