// Generated by AI on 05/04/2026
import Typography from '@mui/material/Typography';
import { LineChart } from '@mui/x-charts/LineChart';
import type { DailySentimentResponse } from '../../api/reflections';

interface Props {
  data: DailySentimentResponse[];
}

export function SentimentTrendChart({ data }: Props) {
  const labels = data.map(d => d.day.slice(0, 3)); // Mon, Tue…
  const positive = data.map(d => d.positive);
  const negative = data.map(d => d.negative);
  const neutral = data.map(d => d.neutral);

  const hasData = data.some(d => d.positive + d.negative + d.neutral > 0);
  if (!hasData) {
    return <Typography variant="body2" color="text.secondary">No sentiment data this week.</Typography>;
  }

  return (
    <LineChart
      xAxis={[{ scaleType: 'point', data: labels }]}
      series={[
        { data: positive, label: 'Positive', color: '#4caf50' },
        { data: negative, label: 'Negative', color: '#f44336' },
        { data: neutral, label: 'Neutral', color: '#9e9e9e' },
      ]}
      height={260}
    />
  );
}
