// Generated by AI on 05/04/2026
using AntarMindAI.Api.Auth;
using AntarMindAI.Api.Services;
using Microsoft.AspNetCore.Authentication;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenApi();
builder.Services.AddControllers();
builder.Services.AddHttpContextAccessor();

// Register ICurrentUserService — LocalDev in Development/Testing, real in production
if (builder.Environment.IsDevelopment() || builder.Environment.IsEnvironment("Testing"))
{
    builder.Services.AddScoped<ICurrentUserService, LocalDevCurrentUserService>();
}
else
{
    builder.Services.AddScoped<ICurrentUserService, CurrentUserService>();
}

// Custom EasyAuth authentication scheme that delegates to ICurrentUserService
builder.Services.AddAuthentication("EasyAuth")
    .AddScheme<AuthenticationSchemeOptions, EasyAuthHandler>("EasyAuth", null);
builder.Services.AddAuthorization();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

// Serve the compiled React frontend from wwwroot/ui
app.UseStaticFiles();
app.MapControllers();

// Fall back to index.html for SPA client-side routing
app.MapFallbackToFile("ui/index.html");

app.Run();

// Required for WebApplicationFactory in integration tests
public partial class Program { }
