// Generated by AI on 05/04/2026
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Api.Services.Insights;

public class CognitiveBiasDetector : ICognitiveBiasDetector
{
    private readonly Dictionary<string, string[]> _patterns;

    public CognitiveBiasDetector(IConfiguration configuration)
    {
        _patterns = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);

        var section = configuration.GetSection("CognitiveBiasDetection:Patterns");
        foreach (var child in section.GetChildren())
        {
            var words = child.GetChildren().Select(c => c.Value ?? string.Empty).ToArray();
            if (words.Length > 0)
                _patterns[child.Key] = words;
        }

        // Built-in defaults if not in config
        if (!_patterns.ContainsKey("Catastrophizing"))
            _patterns["Catastrophizing"] = ["always", "never", "everything", "nothing", "completely", "totally", "ruined", "disaster", "terrible", "worst"];
        if (!_patterns.ContainsKey("Overgeneralizing"))
            _patterns["Overgeneralizing"] = ["everyone", "nobody", "all", "none", "constantly", "typical"];
        if (!_patterns.ContainsKey("BlackAndWhiteThinking"))
            _patterns["BlackAndWhiteThinking"] = ["either", "perfect", "failure", "completely", "totally"];
    }

    public IReadOnlyList<InsightMessage> Analyze(PatternAnalysisContext context)
    {
        var insights = new List<InsightMessage>();
        var now = DateTimeOffset.UtcNow;
        var thoughts = context.Thoughts;

        foreach (var (biasName, keywords) in _patterns)
        {
            // For each thought, collect which keywords match
            var matchingThoughts = new List<(string ThoughtText, string[] MatchedWords)>();

            foreach (var thought in thoughts)
            {
                var lower = thought.Text.ToLowerInvariant();
                var tokens = lower.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                var matched = keywords.Where(kw => tokens.Contains(kw)).Distinct().ToArray();

                if (matched.Length >= 2)
                    matchingThoughts.Add((thought.Text, matched));
            }

            if (matchingThoughts.Count >= 3)
            {
                var topWords = matchingThoughts
                    .SelectMany(m => m.MatchedWords)
                    .GroupBy(w => w)
                    .OrderByDescending(g => g.Count())
                    .Take(2)
                    .Select(g => $"'{g.Key}'")
                    .ToList();

                var wordList = string.Join(", ", topWords);
                var confidence = Math.Round(Math.Min(1.0, matchingThoughts.Count / 10.0), 2);

                insights.Add(new InsightMessage(
                    Category: "CognitiveBias",
                    Message: $"Your recent thoughts show signs of {biasName} — using absolute language like {wordList} frequently.",
                    Confidence: confidence,
                    GeneratedAt: now));
            }
        }

        return insights;
    }
}
