// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services.Insights;

public class CrossCorrelationAnalyzer : ICrossCorrelationAnalyzer
{
    public IReadOnlyList<InsightMessage> Analyze(PatternAnalysisContext context)
    {
        var insights = new List<InsightMessage>();
        var thoughts = context.Thoughts;
        var now = DateTimeOffset.UtcNow;

        if (thoughts.Count < 5)
            return insights;

        // ── Tag co-occurrence rate ─────────────────────────────────────────
        // Collect all tags
        var allTags = thoughts.SelectMany(t => t.Tags).Distinct(StringComparer.OrdinalIgnoreCase).ToList();

        for (int i = 0; i < allTags.Count; i++)
        {
            for (int j = i + 1; j < allTags.Count; j++)
            {
                var tagA = allTags[i];
                var tagB = allTags[j];

                var withA = thoughts.Where(t => t.Tags.Contains(tagA, StringComparer.OrdinalIgnoreCase)).ToList();
                var coOccurCount = withA.Count(t => t.Tags.Contains(tagB, StringComparer.OrdinalIgnoreCase));

                if (coOccurCount < 5) continue;

                var rate = (double)coOccurCount / withA.Count;
                if (rate > 0.6)
                {
                    insights.Add(new InsightMessage(
                        Category: "Correlation",
                        Message: $"{tagA} and {tagB} frequently appear together ({Math.Round(rate * 100)}% co-occurrence).",
                        Confidence: Math.Round(rate, 2),
                        GeneratedAt: now));
                }
            }
        }

        // ── Time-windowed stress/trading correlation ───────────────────────
        var stressNeg = thoughts
            .Where(t => t.Sentiment == "Negative" && t.Tags.Contains("Stress", StringComparer.OrdinalIgnoreCase))
            .ToList();

        int tradingPrecedesCount = 0;
        foreach (var stressThought in stressNeg)
        {
            var window = stressThought.CreatedAt.AddHours(-2);
            var hasPrecedingTrading = thoughts.Any(t =>
                t.CreatedAt >= window &&
                t.CreatedAt < stressThought.CreatedAt &&
                t.Tags.Contains("Trading", StringComparer.OrdinalIgnoreCase));

            if (hasPrecedingTrading) tradingPrecedesCount++;
        }

        if (tradingPrecedesCount >= 3)
        {
            insights.Add(new InsightMessage(
                Category: "Correlation",
                Message: $"Trading-related thoughts frequently precede stress entries within 2 hours ({tradingPrecedesCount} times).",
                Confidence: Math.Round(Math.Min(1.0, tradingPrecedesCount / 10.0), 2),
                GeneratedAt: now));
        }

        return insights;
    }
}
