// Generated by AI on 05/04/2026
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Api.Services.Insights;

public class FrequencyAnalyzer : IFrequencyAnalyzer
{
    private readonly int _windowDays;

    public FrequencyAnalyzer(IConfiguration configuration)
    {
        _windowDays = configuration.GetValue("PatternDetection:FrequencyWindowDays", 7);
    }

    public IReadOnlyList<InsightMessage> Analyze(PatternAnalysisContext context)
    {
        var insights = new List<InsightMessage>();
        var cutoff = DateTimeOffset.UtcNow.AddDays(-_windowDays);
        var windowThoughts = context.Thoughts.Where(t => t.CreatedAt >= cutoff).ToList();

        if (windowThoughts.Count == 0)
            return insights;

        // Count occurrences of each tag across all thoughts in the window
        var tagCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        foreach (var thought in windowThoughts)
        {
            foreach (var tag in thought.Tags)
            {
                tagCounts.TryGetValue(tag, out var count);
                tagCounts[tag] = count + 1;
            }
        }

        var total = windowThoughts.Count;
        var now = DateTimeOffset.UtcNow;

        foreach (var (tag, count) in tagCounts.OrderByDescending(kv => kv.Value))
        {
            var percentage = (double)count / total * 100.0;

            if (percentage >= 25.0)
            {
                var confidence = Math.Min(1.0, percentage / 100.0 * 2.5);
                insights.Add(new InsightMessage(
                    Category: "Frequency",
                    Message: $"{tag} is your most frequent thought category this week ({percentage:F0}% of thoughts).",
                    Confidence: Math.Round(confidence, 2),
                    GeneratedAt: now));
            }
            else if (count >= 5)
            {
                insights.Add(new InsightMessage(
                    Category: "Frequency",
                    Message: $"{tag} has appeared frequently in your thoughts lately.",
                    Confidence: Math.Round(Math.Min(1.0, count / 10.0), 2),
                    GeneratedAt: now));
            }
        }

        return insights;
    }
}
