// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services.Insights;

public record InsightMessage(
    string Category,
    string Message,
    double Confidence,
    DateTimeOffset GeneratedAt);
