// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;

namespace AntarMindAI.Api.Services.Insights;

public class PatternAnalysisContext
{
    public IReadOnlyList<ThoughtEntry> Thoughts { get; }
    public int ThoughtCount => Thoughts.Count;
    public int WindowDays { get; }

    public PatternAnalysisContext(IReadOnlyList<ThoughtEntry> thoughts, int windowDays)
    {
        Thoughts = thoughts;
        WindowDays = windowDays;
    }
}
