// Generated by AI on 05/04/2026
using System.Text;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Api.Services.Insights;

public class RepetitionDetector : IRepetitionDetector
{
    private readonly ITextPreprocessor _preprocessor;
    private readonly double _similarityThreshold;

    public RepetitionDetector(ITextPreprocessor preprocessor, IConfiguration configuration)
    {
        _preprocessor = preprocessor;
        _similarityThreshold = configuration.GetValue("PatternDetection:RepetitionSimilarityThreshold", 0.3);
    }

    public IReadOnlyList<InsightMessage> Analyze(PatternAnalysisContext context)
    {
        var thoughts = context.Thoughts;
        if (thoughts.Count < 3)
            return [];

        // Tokenise each thought once
        var tokenSets = thoughts
            .Select(t => (Thought: t, Tokens: new HashSet<string>(_preprocessor.Tokenize(t.Text), StringComparer.OrdinalIgnoreCase)))
            .ToList();

        // Union-Find: parent[i] = representative of cluster containing i
        var parent = Enumerable.Range(0, thoughts.Count).ToArray();

        int Find(int x)
        {
            while (parent[x] != x) { parent[x] = parent[parent[x]]; x = parent[x]; }
            return x;
        }

        void Union(int a, int b)
        {
            a = Find(a); b = Find(b);
            if (a != b) parent[b] = a;
        }

        for (int i = 0; i < tokenSets.Count; i++)
        {
            for (int j = i + 1; j < tokenSets.Count; j++)
            {
                var setA = tokenSets[i].Tokens;
                var setB = tokenSets[j].Tokens;

                if (setA.Count == 0 || setB.Count == 0)
                    continue;

                var intersection = setA.Intersect(setB).Count();
                var union = setA.Union(setB).Count();
                var jaccard = (double)intersection / union;

                if (jaccard >= _similarityThreshold)
                    Union(i, j);
            }
        }

        // Group by cluster representative
        var clusters = new Dictionary<int, List<int>>();
        for (int i = 0; i < thoughts.Count; i++)
        {
            var rep = Find(i);
            if (!clusters.TryGetValue(rep, out var list))
            {
                list = [];
                clusters[rep] = list;
            }
            list.Add(i);
        }

        var insights = new List<InsightMessage>();
        var now = DateTimeOffset.UtcNow;

        foreach (var (_, indices) in clusters)
        {
            if (indices.Count < 3)
                continue;

            // Find top shared keywords across cluster members
            var allTokens = indices
                .SelectMany(idx => tokenSets[idx].Tokens)
                .GroupBy(t => t, StringComparer.OrdinalIgnoreCase)
                .OrderByDescending(g => g.Count())
                .Take(3)
                .Select(g => g.Key)
                .ToList();

            var sb = new StringBuilder();
            for (int k = 0; k < allTokens.Count; k++)
            {
                if (k > 0) sb.Append(k == allTokens.Count - 1 ? " and " : ", ");
                sb.Append(allTokens[k]);
            }

            var keywords = sb.Length > 0 ? sb.ToString() : "similar topics";
            var confidence = Math.Round(Math.Min(1.0, indices.Count / 10.0), 2);

            insights.Add(new InsightMessage(
                Category: "Repetition",
                Message: $"You've logged similar thoughts about {keywords} {indices.Count} times recently.",
                Confidence: confidence,
                GeneratedAt: now));
        }

        return insights;
    }
}
