// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services.Insights;

public class TimeTrendAnalyzer : ITimeTrendAnalyzer
{
    public IReadOnlyList<InsightMessage> Analyze(PatternAnalysisContext context)
    {
        var insights = new List<InsightMessage>();
        var thoughts = context.Thoughts;
        var now = DateTimeOffset.UtcNow;

        if (thoughts.Count < 5)
            return insights;

        // ── Peak negative hour window ──────────────────────────────────────────
        // Count negative thoughts per hour-of-day bucket
        var negativeByHour = new int[24];
        var totalByHour = new int[24];

        foreach (var thought in thoughts)
        {
            var hour = thought.CreatedAt.ToLocalTime().Hour;
            totalByHour[hour]++;
            if (thought.Sentiment == "Negative")
                negativeByHour[hour]++;
        }

        // Sliding 4-hour window — find window with highest negative rate
        double bestRate = 0.0;
        int bestWindowStart = -1;

        for (int start = 0; start < 24; start++)
        {
            int totalInWindow = 0;
            int negInWindow = 0;
            for (int offset = 0; offset < 4; offset++)
            {
                var h = (start + offset) % 24;
                totalInWindow += totalByHour[h];
                negInWindow += negativeByHour[h];
            }

            if (totalInWindow >= 3)
            {
                var rate = (double)negInWindow / totalInWindow;
                if (rate > bestRate && rate >= 0.6)
                {
                    bestRate = rate;
                    bestWindowStart = start;
                }
            }
        }

        if (bestWindowStart >= 0)
        {
            var endHour = (bestWindowStart + 4) % 24;
            var startLabel = FormatHour(bestWindowStart);
            var endLabel = FormatHour(endHour);
            insights.Add(new InsightMessage(
                Category: "TimeTrend",
                Message: $"Negative thoughts peak between {startLabel} and {endLabel}.",
                Confidence: Math.Round(bestRate, 2),
                GeneratedAt: now));
        }

        // ── Peak activity day ──────────────────────────────────────────────────
        var countByDay = new int[7];
        foreach (var thought in thoughts)
        {
            var day = (int)thought.CreatedAt.ToLocalTime().DayOfWeek;
            countByDay[day]++;
        }

        var maxDayCount = countByDay.Max();
        if (maxDayCount >= 2)
        {
            var peakDay = (DayOfWeek)Array.IndexOf(countByDay, maxDayCount);
            insights.Add(new InsightMessage(
                Category: "TimeTrend",
                Message: $"You log the most thoughts on {peakDay}.",
                Confidence: Math.Round(Math.Min(1.0, maxDayCount / (double)thoughts.Count * 3.0), 2),
                GeneratedAt: now));
        }

        return insights;
    }

    private static string FormatHour(int hour)
    {
        if (hour == 0) return "12 AM";
        if (hour < 12) return $"{hour} AM";
        if (hour == 12) return "12 PM";
        return $"{hour - 12} PM";
    }
}
