// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services.Insights;

public class TriggerIdentifier : ITriggerIdentifier
{
    public IReadOnlyList<InsightMessage> Analyze(PatternAnalysisContext context)
    {
        var insights = new List<InsightMessage>();
        var thoughts = context.Thoughts;
        var now = DateTimeOffset.UtcNow;

        if (thoughts.Count == 0)
            return insights;

        // ── Per-domain negative rate ──────────────────────────────────────────
        var domainTotal = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        var domainNegative = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);

        foreach (var thought in thoughts)
        {
            foreach (var tag in thought.Tags)
            {
                domainTotal.TryGetValue(tag, out var total);
                domainTotal[tag] = total + 1;

                if (thought.Sentiment == "Negative")
                {
                    domainNegative.TryGetValue(tag, out var neg);
                    domainNegative[tag] = neg + 1;
                }
            }
        }

        foreach (var (tag, total) in domainTotal)
        {
            if (total < 3) continue;

            domainNegative.TryGetValue(tag, out var negCount);
            var negRate = (double)negCount / total;

            if (negRate >= 0.5)
            {
                var confidence = Math.Round(negRate, 2);
                insights.Add(new InsightMessage(
                    Category: "Trigger",
                    Message: $"Many of your {tag}-related thoughts carry a negative tone — this domain may be a stress trigger.",
                    Confidence: confidence,
                    GeneratedAt: now));
            }
        }

        // ── Stress co-occurrence ──────────────────────────────────────────────
        var stressThoughts = thoughts.Where(t => t.Tags.Contains("Stress", StringComparer.OrdinalIgnoreCase)).ToList();
        if (stressThoughts.Count == 0)
            return insights;

        var coTagTotal = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        foreach (var thought in stressThoughts)
        {
            foreach (var tag in thought.Tags)
            {
                if (string.Equals(tag, "Stress", StringComparison.OrdinalIgnoreCase)) continue;
                coTagTotal.TryGetValue(tag, out var cnt);
                coTagTotal[tag] = cnt + 1;
            }
        }

        foreach (var (coTag, coCount) in coTagTotal)
        {
            var coRate = (double)coCount / stressThoughts.Count;
            if (coRate >= 0.6)
            {
                insights.Add(new InsightMessage(
                    Category: "Trigger",
                    Message: $"{coTag} frequently appears alongside stress-related thoughts.",
                    Confidence: Math.Round(coRate, 2),
                    GeneratedAt: now));
            }
        }

        return insights;
    }
}
