// Generated by AI on 05/04/2026
using System.Text;
using AntarMindAI.Api.Repositories;
using AntarMindAI.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AntarMindAI.Api.Controllers.Export;

[ApiController]
[Authorize]
[Route("api/export")]
public class ExportController : ControllerBase
{
    private readonly IThoughtRepository _repository;
    private readonly ICurrentUserService _currentUserService;

    public ExportController(IThoughtRepository repository, ICurrentUserService currentUserService)
    {
        _repository = repository;
        _currentUserService = currentUserService;
    }

    [HttpGet]
    public async Task<IActionResult> ExportThoughtsAsync([FromQuery] string format = "json")
    {
        var userId = _currentUserService.GetUserId() ?? "anonymous";
        var thoughts = await _repository.GetAllByUserAsync(userId);
        var dateStamp = DateTimeOffset.UtcNow.ToString("yyyy-MM-dd");

        if (string.Equals(format, "csv", StringComparison.OrdinalIgnoreCase))
        {
            var sb = new StringBuilder();
            sb.AppendLine("Id,Text,CreatedAt,Tags,Sentiment,IntensityScore");

            foreach (var t in thoughts)
            {
                var text = EscapeCsvField(t.Text);
                var tags = EscapeCsvField(string.Join(";", t.Tags));
                sb.AppendLine($"{t.Id},{text},{t.CreatedAt:o},{tags},{t.Sentiment},{t.IntensityScore}");
            }

            var bytes = Encoding.UTF8.GetBytes(sb.ToString());
            return File(bytes, "text/csv", $"thoughts-export-{dateStamp}.csv");
        }

        if (string.Equals(format, "json", StringComparison.OrdinalIgnoreCase))
        {
            var items = thoughts.Select(t => new
            {
                t.Id, t.Text, t.CreatedAt, t.Tags, t.Sentiment, t.IntensityScore
            });
            return Ok(items);
        }

        return BadRequest(new
        {
            correlationId = HttpContext.TraceIdentifier,
            status = 400,
            title = "Unsupported format",
            detail = "Supported formats are 'csv' and 'json'.",
            source = "format"
        });
    }

    private static string EscapeCsvField(string value)
    {
        if (value.Contains(',') || value.Contains('"') || value.Contains('\n'))
            return $"\"{value.Replace("\"", "\"\"")}\"";
        return value;
    }
}
