// Generated by AI on 05/04/2026

export interface InsightMessageResponse {
  category: string;
  message: string;
  confidence: number;
  generatedAt: string;
}

export interface InsightsResponse {
  insights: InsightMessageResponse[];
  thoughtCount: number;
  analysisWindowDays: number;
}

export async function getInsights(): Promise<InsightsResponse> {
  const response = await fetch('/api/insights');

  if (!response.ok) {
    const error = await response.json().catch(() => ({ title: 'Request failed' }));
    throw new Error((error as { title?: string }).title ?? 'Failed to load insights');
  }

  return response.json() as Promise<InsightsResponse>;
}
