// Generated by AI on 05/04/2026

export interface CategoryCountResponse {
  category: string;
  count: number;
  percentage: number;
}

export interface DailySentimentResponse {
  day: string;
  positive: number;
  negative: number;
  neutral: number;
}

export interface HourlyActivityResponse {
  hour: number;
  thoughtCount: number;
}

export interface InsightMessageResponse {
  category: string;
  message: string;
  confidence: number;
}

export interface WeeklyReflectionResponse {
  weekStart: string;
  weekEnd: string;
  totalThoughts: number;
  categoryDistribution: CategoryCountResponse[];
  dailySentimentTrend: DailySentimentResponse[];
  peakActivityByHour: HourlyActivityResponse[];
  topInsights: InsightMessageResponse[];
  aiSummary: string | null;
}

export async function getWeeklyReflection(weekDate?: string): Promise<WeeklyReflectionResponse> {
  const url = weekDate
    ? `/api/reflections/weekly?weekDate=${encodeURIComponent(weekDate)}`
    : '/api/reflections/weekly';

  const response = await fetch(url);

  if (!response.ok) {
    const error = await response.json().catch(() => ({ title: 'Request failed' }));
    throw new Error((error as { title?: string }).title ?? 'Failed to load weekly reflection');
  }

  return response.json() as Promise<WeeklyReflectionResponse>;
}
