// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Controllers.Thoughts;

public record CreateThoughtRequest(string Text);

public record ThoughtResponse(string Id, string Text, DateTimeOffset CreatedAt);

public record PagedThoughtsResponse(IReadOnlyList<ThoughtResponse> Items, int TotalCount, int Page, int PageSize);
