// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Repositories;
using AntarMindAI.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AntarMindAI.Api.Controllers.Thoughts;

[ApiController]
[Route("api/thoughts")]
[Authorize]
public class ThoughtsController : ControllerBase
{
    private readonly IThoughtRepository _repository;
    private readonly ICurrentUserService _currentUser;

    public ThoughtsController(IThoughtRepository repository, ICurrentUserService currentUser)
    {
        _repository = repository;
        _currentUser = currentUser;
    }

    [HttpPost]
    public async Task<IActionResult> CreateThoughtAsync([FromBody] CreateThoughtRequest request)
    {
        Response.Headers.CacheControl = "no-store";

        if (string.IsNullOrWhiteSpace(request.Text) || request.Text.Length > 2000)
        {
            return BadRequest(new
            {
                correlationId = Guid.NewGuid().ToString(),
                status = "400",
                title = "Validation Error",
                detail = "Text must be between 1 and 2000 characters.",
                source = new { text = "Text must be between 1 and 2000 characters." }
            });
        }

        var userId = _currentUser.GetUserId() ?? "anonymous";
        var entry = new ThoughtEntry
        {
            Id = Guid.NewGuid().ToString(),
            UserId = userId,
            Text = request.Text.Trim(),
            CreatedAt = DateTimeOffset.UtcNow
        };

        var created = await _repository.CreateAsync(entry);
        var response = new ThoughtResponse(created.Id, created.Text, created.CreatedAt);

        return Created($"/api/thoughts/{created.Id}", response);
    }

    [HttpGet]
    public async Task<IActionResult> GetThoughtsAsync([FromQuery] int page = 1, [FromQuery] int pageSize = 20)
    {
        Response.Headers.CacheControl = "no-store";

        if (page < 1) page = 1;
        if (pageSize < 1) pageSize = 20;
        if (pageSize > 100) pageSize = 100;

        var userId = _currentUser.GetUserId() ?? "anonymous";
        var (items, total) = await _repository.GetByUserAsync(userId, page, pageSize);

        var response = new PagedThoughtsResponse(
            Items: items.Select(e => new ThoughtResponse(e.Id, e.Text, e.CreatedAt)).ToList(),
            TotalCount: total,
            Page: page,
            PageSize: pageSize
        );

        return Ok(response);
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteThoughtAsync(string id)
    {
        Response.Headers.CacheControl = "no-store";

        var userId = _currentUser.GetUserId() ?? "anonymous";
        var deleted = await _repository.DeleteAsync(id, userId);

        if (!deleted)
        {
            return NotFound(new
            {
                correlationId = Guid.NewGuid().ToString(),
                status = "404",
                title = "Not Found",
                detail = $"Thought with id '{id}' was not found or does not belong to the current user."
            });
        }

        return NoContent();
    }
}
