// Generated by AI on 05/04/2026
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AntarMindAI.Api.Controllers;

[ApiController]
[Route("api")]
public class HealthController : ControllerBase
{
    /// <summary>
    /// Liveness check endpoint. Anonymous access allowed.
    /// </summary>
    [HttpGet("health")]
    [AllowAnonymous]
    public IActionResult GetHealth() => Ok(new { status = "ok" });
}
