// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;
using System.Security.Claims;
using System.Text.Encodings.Web;

namespace AntarMindAI.Api.Auth;

/// <summary>
/// Authentication handler that reads Azure App Service EasyAuth headers
/// and builds a ClaimsPrincipal from them.
/// </summary>
public class EasyAuthHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    private readonly ICurrentUserService _currentUserService;

    public EasyAuthHandler(
        IOptionsMonitor<AuthenticationSchemeOptions> options,
        ILoggerFactory logger,
        UrlEncoder encoder,
        ICurrentUserService currentUserService)
        : base(options, logger, encoder)
    {
        _currentUserService = currentUserService;
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var userId = _currentUserService.GetUserId();
        var userEmail = _currentUserService.GetUserEmail();

        if (string.IsNullOrEmpty(userId))
        {
            return Task.FromResult(AuthenticateResult.NoResult());
        }

        var claims = new[]
        {
            new Claim(ClaimTypes.NameIdentifier, userId),
            new Claim(ClaimTypes.Email, userEmail ?? string.Empty),
        };

        var identity = new ClaimsIdentity(claims, Scheme.Name);
        var principal = new ClaimsPrincipal(identity);
        var ticket = new AuthenticationTicket(principal, Scheme.Name);

        return Task.FromResult(AuthenticateResult.Success(ticket));
    }
}
