// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using System.ComponentModel.DataAnnotations;

namespace AntarMindAI.Tests.Models;

public class ThoughtEntryTests
{
    [Fact]
    public void ThoughtEntry_DefaultValues_AreEmpty()
    {
        var entry = new ThoughtEntry();

        Assert.Equal(string.Empty, entry.Id);
        Assert.Equal(string.Empty, entry.UserId);
        Assert.Equal(string.Empty, entry.Text);
        Assert.Equal(default, entry.CreatedAt);
    }

    [Fact]
    public void ThoughtEntry_CanBeConstructedWithAllProperties()
    {
        var now = DateTimeOffset.UtcNow;
        var entry = new ThoughtEntry
        {
            Id = "test-id",
            UserId = "user-1",
            Text = "A thought",
            CreatedAt = now
        };

        Assert.Equal("test-id", entry.Id);
        Assert.Equal("user-1", entry.UserId);
        Assert.Equal("A thought", entry.Text);
        Assert.Equal(now, entry.CreatedAt);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void ThoughtEntry_Text_CanBeEmptyOrWhitespace_ModelAllowsIt(string text)
    {
        // Validation is enforced at the controller layer, not the model layer
        var entry = new ThoughtEntry { Text = text };
        Assert.Equal(text, entry.Text);
    }

    [Fact]
    public void ThoughtEntry_Text_CanBe2000Characters()
    {
        var longText = new string('a', 2000);
        var entry = new ThoughtEntry { Text = longText };
        Assert.Equal(2000, entry.Text.Length);
    }

    [Fact]
    public void ThoughtEntry_UsesDateTimeOffset_NotDateTime()
    {
        // Ensure CreatedAt is DateTimeOffset (not DateTime) for timezone correctness
        var entry = new ThoughtEntry();
        Assert.IsType<DateTimeOffset>(entry.CreatedAt);
    }
}
