// Generated by AI on 05/04/2026
using Azure;
using Azure.Data.Tables;
using AntarMindAI.Api.Models;

namespace AntarMindAI.Api.Repositories;

public class AzureTableStorageThoughtRepository : IThoughtRepository
{
    private const string TableName = "thoughts";
    private readonly TableClient _tableClient;

    public AzureTableStorageThoughtRepository(string connectionString)
    {
        var serviceClient = new TableServiceClient(connectionString);
        _tableClient = serviceClient.GetTableClient(TableName);
        _tableClient.CreateIfNotExists();
    }

    public async Task<ThoughtEntry> CreateAsync(ThoughtEntry entry)
    {
        var rowKey = (DateTimeOffset.MaxValue.Ticks - entry.CreatedAt.Ticks).ToString("D20");
        var tableEntity = new TableEntity(entry.UserId, rowKey)
        {
            ["Id"] = entry.Id,
            ["Text"] = entry.Text,
            ["CreatedAt"] = entry.CreatedAt
        };

        await _tableClient.AddEntityAsync(tableEntity);
        return entry;
    }

    public async Task<(IReadOnlyList<ThoughtEntry> Items, int TotalCount)> GetByUserAsync(string userId, int page, int pageSize)
    {
        var allEntries = new List<ThoughtEntry>();
        string? continuationToken = null;

        // Fetch all entries for user (partition) — needed for total count and page offset
        do
        {
            var page_ = await _tableClient.QueryAsync<TableEntity>(
                filter: $"PartitionKey eq '{userId}'",
                maxPerPage: 1000
            ).AsPages(continuationToken).FirstOrDefaultAsync();

            if (page_ is null) break;

            foreach (var entity in page_.Values)
            {
                allEntries.Add(MapToEntry(entity, userId));
            }

            continuationToken = page_.ContinuationToken;
        } while (continuationToken is not null);

        var total = allEntries.Count;
        var skip = (page - 1) * pageSize;
        // Entries are already in reverse-chronological order due to inverted RowKey
        var items = allEntries.Skip(skip).Take(pageSize).ToList();

        return (items, total);
    }

    public async Task<bool> DeleteAsync(string id, string userId)
    {
        // Find the entity by Id property within the user's partition
        var entities = _tableClient.QueryAsync<TableEntity>(
            filter: $"PartitionKey eq '{userId}' and Id eq '{id}'"
        );

        await foreach (var entity in entities)
        {
            await _tableClient.DeleteEntityAsync(entity.PartitionKey, entity.RowKey, entity.ETag);
            return true;
        }

        return false;
    }

    private static ThoughtEntry MapToEntry(TableEntity entity, string userId)
    {
        return new ThoughtEntry
        {
            Id = entity.GetString("Id") ?? string.Empty,
            UserId = userId,
            Text = entity.GetString("Text") ?? string.Empty,
            CreatedAt = entity.GetDateTimeOffset("CreatedAt") ?? DateTimeOffset.MinValue
        };
    }
}
