// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;

namespace AntarMindAI.Api.Repositories;

public interface IThoughtRepository
{
    Task<ThoughtEntry> CreateAsync(ThoughtEntry entry);
    Task<(IReadOnlyList<ThoughtEntry> Items, int TotalCount)> GetByUserAsync(string userId, int page, int pageSize);
    /// <summary>
    /// Deletes a thought by id. Returns false if not found or not owned by userId.
    /// </summary>
    Task<bool> DeleteAsync(string id, string userId);
}
