// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services.Insights;

namespace AntarMindAI.Api.Services.Reflections;

public interface IRecommendationService
{
    IReadOnlyList<string> GetRecommendations(WeeklyReflection reflection, IReadOnlyList<InsightMessage> insights);
}
