// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Services.Reflections;

public interface IWeeklyReflectionService
{
    Task<WeeklyReflection> GetWeeklyReflectionAsync(string userId, DateTimeOffset? weekDate = null);
}
