// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services.Insights;

namespace AntarMindAI.Api.Services.Reflections;

public class RecommendationService : IRecommendationService
{
    public IReadOnlyList<string> GetRecommendations(WeeklyReflection reflection, IReadOnlyList<InsightMessage> insights)
    {
        var recommendations = new List<string>();

        // Rule 1: Evening stress — peak negative activity in hours 19–22
        var eveningHours = reflection.PeakActivityByHour
            .Where(h => h.Hour >= 19 && h.Hour <= 22)
            .Sum(h => h.ThoughtCount);

        var totalNegative = reflection.DailySentimentTrend.Sum(d => d.Negative);
        if (eveningHours > 0 && totalNegative > 0)
        {
            // Check if there is an evening-related stress insight or enough negative evening thoughts
            var hasEveningStress = insights.Any(i =>
                i.Category == "TimeTrend" && i.Message.Contains("evening", StringComparison.OrdinalIgnoreCase)) ||
                eveningHours >= 3;

            if (hasEveningStress)
            {
                recommendations.Add(
                    "Consider a mindfulness practice before 7 PM to interrupt the evening stress pattern.");
            }
        }

        // Rule 2: Trading-heavy thinking (Trading > 40% of categories)
        var tradingCategory = reflection.CategoryDistribution
            .FirstOrDefault(c => c.Category.Equals("Trading", StringComparison.OrdinalIgnoreCase));

        if (tradingCategory is not null && tradingCategory.Percentage > 40.0)
        {
            recommendations.Add(
                "Your thinking is heavily trading-focused. Consider a deliberate mental shutdown ritual at market close.");
        }

        // Rule 3: High overall negativity (>50% negative days)
        var negativeDays = reflection.DailySentimentTrend.Count(d => d.Negative > d.Positive);
        if (negativeDays >= 4)
        {
            recommendations.Add(
                "More than half your week shows negative thought patterns. A daily 5-minute gratitude journaling exercise may help shift perspective.");
        }

        return recommendations.Take(3).ToList();
    }
}
