// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services.Insights;
using AntarMindAI.Api.Services.Reflections;

namespace AntarMindAI.Tests.Services.Reflections;

public class RecommendationServiceTests
{
    private static RecommendationService Create() => new();

    private static WeeklyReflection EmptyReflection(
        IReadOnlyList<CategoryCount>? categories = null,
        IReadOnlyList<DailySentiment>? daily = null,
        IReadOnlyList<HourlyActivity>? hourly = null) =>
        new(
            WeekStart: DateTimeOffset.UtcNow.AddDays(-7),
            WeekEnd: DateTimeOffset.UtcNow,
            TotalThoughts: 0,
            CategoryDistribution: categories ?? [],
            DailySentimentTrend: daily ?? BuildEmptyDaily(),
            PeakActivityByHour: hourly ?? BuildEmptyHourly(),
            TopInsights: [],
            AiSummary: null,
            Recommendations: []);

    private static IReadOnlyList<DailySentiment> BuildEmptyDaily() =>
        Enumerable.Range(0, 7)
            .Select(i => new DailySentiment((DayOfWeek)i, 0, 0, 0))
            .ToList();

    private static IReadOnlyList<HourlyActivity> BuildEmptyHourly() =>
        Enumerable.Range(0, 24)
            .Select(h => new HourlyActivity(h, 0))
            .ToList();

    [Fact]
    public void GetRecommendations_TradingHeavy_ReturnsTradingRecommendation()
    {
        var svc = Create();
        var categories = new List<CategoryCount>
        {
            new("Trading", 50, 50.0),
            new("Work", 30, 30.0),
            new("Health", 20, 20.0)
        };

        var reflection = EmptyReflection(categories: categories);
        var recs = svc.GetRecommendations(reflection, []);

        Assert.Contains(recs, r => r.Contains("trading-focused", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void GetRecommendations_EveningStress_ReturnsEveningRecommendation()
    {
        var svc = Create();
        var hourly = Enumerable.Range(0, 24)
            .Select(h => new HourlyActivity(h, h >= 19 && h <= 22 ? 4 : 0))
            .ToList();
        var daily = Enumerable.Range(0, 7)
            .Select(i => new DailySentiment((DayOfWeek)i, 0, 2, 0))
            .ToList();

        var reflection = EmptyReflection(hourly: hourly, daily: daily);
        var recs = svc.GetRecommendations(reflection, []);

        Assert.Contains(recs, r => r.Contains("mindfulness", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void GetRecommendations_NoPatterns_ReturnsEmpty()
    {
        var svc = Create();
        var reflection = EmptyReflection();
        var recs = svc.GetRecommendations(reflection, []);

        Assert.Empty(recs);
    }
}
