// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services.Insights;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Tests.Services.Insights;

public class CognitiveBiasDetectorTests
{
    private static CognitiveBiasDetector CreateDetector() =>
        new(new ConfigurationBuilder().Build());

    private static ThoughtEntry Thought(string text, int daysAgo = 0) =>
        new()
        {
            Id = Guid.NewGuid().ToString(),
            UserId = "u1",
            Text = text,
            Tags = [],
            Sentiment = "Negative",
            CreatedAt = DateTimeOffset.UtcNow.AddDays(-daysAgo)
        };

    [Fact]
    public void Analyze_CatastrophizingPattern_ThreeMatchingThoughts_ReturnsInsight()
    {
        var detector = CreateDetector();
        var thoughts = new List<ThoughtEntry>
        {
            Thought("everything is always a disaster"),
            Thought("this is totally ruined and nothing will work"),
            Thought("the worst case is everything will fail completely"),
            Thought("I always never succeed in anything")
        };

        var context = new PatternAnalysisContext(thoughts, 7);
        var insights = detector.Analyze(context);

        Assert.NotEmpty(insights);
        Assert.Contains(insights, i => i.Category == "CognitiveBias" && i.Message.Contains("Catastrophizing"));
    }

    [Fact]
    public void Analyze_OvergeneralizingPattern_ThreeMatchingThoughts_ReturnsInsight()
    {
        var detector = CreateDetector();
        var thoughts = new List<ThoughtEntry>
        {
            Thought("everyone always does this to me and nobody cares"),
            Thought("nobody ever understands, everyone is like this constantly"),
            Thought("everyone does this constantly and nobody ever helps"),
            Thought("typical that everyone would act this way, nobody cares")
        };

        var context = new PatternAnalysisContext(thoughts, 7);
        var insights = detector.Analyze(context);

        Assert.NotEmpty(insights);
        Assert.Contains(insights, i => i.Category == "CognitiveBias" && i.Message.Contains("Overgeneralizing"));
    }

    [Fact]
    public void Analyze_BelowThreshold_ReturnsNoInsights()
    {
        var detector = CreateDetector();
        var thoughts = new List<ThoughtEntry>
        {
            Thought("everything is always bad"),
            Thought("just a normal day at work")
        };

        var context = new PatternAnalysisContext(thoughts, 7);
        var insights = detector.Analyze(context);

        Assert.DoesNotContain(insights, i => i.Category == "CognitiveBias");
    }
}
