// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services.Insights;

namespace AntarMindAI.Tests.Services.Insights;

public class CrossCorrelationAnalyzerTests
{
    private static CrossCorrelationAnalyzer CreateAnalyzer() => new();

    private static ThoughtEntry Thought(string[] tags, string sentiment = "Neutral", int minutesAgo = 0) =>
        new()
        {
            Id = Guid.NewGuid().ToString(),
            UserId = "u1",
            Text = "test thought",
            Tags = tags,
            Sentiment = sentiment,
            CreatedAt = DateTimeOffset.UtcNow.AddMinutes(-minutesAgo)
        };

    [Fact]
    public void Analyze_HighCoOccurrence_ReturnsCorrelationInsight()
    {
        var analyzer = CreateAnalyzer();

        // 6 thoughts where Work appears with Trading (≥5 co-occurrences, 100% rate)
        var thoughts = Enumerable.Range(0, 6)
            .Select(i => Thought(["Work", "Trading"]))
            .ToList<ThoughtEntry>();

        var context = new PatternAnalysisContext(thoughts, 7);
        var insights = analyzer.Analyze(context);

        Assert.Contains(insights, i => i.Category == "Correlation");
    }

    [Fact]
    public void Analyze_LowCoOccurrence_NoInsight()
    {
        var analyzer = CreateAnalyzer();

        // 5 Work thoughts, only 2 also have Trading (40% < 60%)
        var thoughts = new List<ThoughtEntry>
        {
            Thought(["Work", "Trading"]), Thought(["Work", "Trading"]),
            Thought(["Work"]), Thought(["Work"]), Thought(["Work"])
        };

        var context = new PatternAnalysisContext(thoughts, 7);
        var insights = analyzer.Analyze(context);

        Assert.DoesNotContain(insights, i => i.Category == "Correlation"
            && i.Message.Contains("Work") && i.Message.Contains("Trading"));
    }

    [Fact]
    public void Analyze_TradingPrecedesStress_ThreeTimes_ReturnsInsight()
    {
        var analyzer = CreateAnalyzer();

        // 3 stress-negative thoughts, each with a Trading thought within 2 hours before
        var thoughts = new List<ThoughtEntry>();
        for (int i = 0; i < 3; i++)
        {
            var offset = i * 300; // space them 5 hours apart
            thoughts.Add(Thought(["Trading"], "Neutral", offset + 90)); // 90 min before stress
            thoughts.Add(Thought(["Stress"], "Negative", offset));      // stress thought
        }

        var context = new PatternAnalysisContext(thoughts, 7);
        var insights = analyzer.Analyze(context);

        Assert.Contains(insights, i => i.Message.Contains("Trading-related thoughts frequently precede"));
    }

    [Fact]
    public void Analyze_TradingPrecedesStress_LessThanThree_NoInsight()
    {
        var analyzer = CreateAnalyzer();

        var thoughts = new List<ThoughtEntry>
        {
            Thought(["Trading"], "Neutral", 90),
            Thought(["Stress"], "Negative", 0)
        };

        var context = new PatternAnalysisContext(thoughts, 7);
        var insights = analyzer.Analyze(context);

        Assert.DoesNotContain(insights, i => i.Message.Contains("Trading-related thoughts frequently precede"));
    }
}
