// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services.Insights;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Tests.Services.Insights;

public class FrequencyAnalyzerTests
{
    private static FrequencyAnalyzer CreateAnalyzer(int windowDays = 7) =>
        new(new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["PatternDetection:FrequencyWindowDays"] = windowDays.ToString()
            })
            .Build());

    private static ThoughtEntry Thought(string[] tags, int daysAgo = 0) =>
        new() { Id = Guid.NewGuid().ToString(), Text = "test", Tags = tags, Sentiment = "Neutral", CreatedAt = DateTimeOffset.UtcNow.AddDays(-daysAgo) };

    [Fact]
    public void Analyze_DominantCategory_Above25Percent_ReturnsFrequencyInsight()
    {
        var analyzer = CreateAnalyzer();
        // 4 out of 5 thoughts tagged Trading = 80%
        var thoughts = new List<ThoughtEntry>
        {
            Thought(["Trading"]), Thought(["Trading"]), Thought(["Trading"]), Thought(["Trading"]),
            Thought(["Work"])
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = analyzer.Analyze(context);

        Assert.Contains(insights, i => i.Category == "Frequency" && i.Message.Contains("Trading"));
    }

    [Fact]
    public void Analyze_TagAppearingFiveTimes_ReturnsFrequentInsight()
    {
        var analyzer = CreateAnalyzer();
        // 5 Work tags in 20 thoughts = 25%, borderline — use 5 of 100 = below 25% threshold but count ≥ 5
        var thoughts = Enumerable.Range(0, 5).Select(_ => Thought(["Work"]))
            .Concat(Enumerable.Range(0, 95).Select(_ => Thought(["Other"])))
            .ToList();
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = analyzer.Analyze(context);

        // Work has 5 occurrences but < 25%; should get "appeared frequently" insight
        Assert.Contains(insights, i => i.Message.Contains("Work") && i.Message.Contains("frequently"));
    }

    [Fact]
    public void Analyze_MultipleTagsBelowThreshold_ReturnsNoInsights()
    {
        var analyzer = CreateAnalyzer();
        // 5 distinct tags each appearing once → each is 20% of 5 total (below 25%) and below ≥5 count threshold
        var thoughts = new List<ThoughtEntry>
        {
            Thought(["Trading"]), Thought(["Work"]), Thought(["Health"]), Thought(["Learning"]), Thought(["Family"])
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = analyzer.Analyze(context);

        Assert.Empty(insights);
    }

    [Fact]
    public void Analyze_EmptyThoughts_ReturnsNoInsights()
    {
        var analyzer = CreateAnalyzer();
        var context = new PatternAnalysisContext([], 7);

        var insights = analyzer.Analyze(context);

        Assert.Empty(insights);
    }

    [Fact]
    public void Analyze_ThoughtsOutsideWindow_AreExcluded()
    {
        var analyzer = CreateAnalyzer(windowDays: 7);
        // Dominant tag but all 10+ days ago (outside window)
        var thoughts = Enumerable.Range(0, 5).Select(_ => Thought(["Trading"], daysAgo: 10)).ToList();
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = analyzer.Analyze(context);

        Assert.Empty(insights);
    }
}
