// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services.Insights;

namespace AntarMindAI.Tests.Services.Insights;

public class PatternAnalysisContextTests
{
    [Fact]
    public void ThoughtCount_ReflectsNumberOfThoughts()
    {
        var thoughts = new List<ThoughtEntry>
        {
            new() { Id = "1", Text = "a", CreatedAt = DateTimeOffset.UtcNow },
            new() { Id = "2", Text = "b", CreatedAt = DateTimeOffset.UtcNow },
            new() { Id = "3", Text = "c", CreatedAt = DateTimeOffset.UtcNow }
        };

        var context = new PatternAnalysisContext(thoughts, windowDays: 7);

        Assert.Equal(3, context.ThoughtCount);
    }

    [Fact]
    public void WindowDays_ReturnsConfiguredValue()
    {
        var context = new PatternAnalysisContext([], windowDays: 14);

        Assert.Equal(14, context.WindowDays);
    }

    [Fact]
    public void Thoughts_AreAccessible()
    {
        var thoughts = new List<ThoughtEntry>
        {
            new() { Id = "1", Text = "test", CreatedAt = DateTimeOffset.UtcNow }
        };

        var context = new PatternAnalysisContext(thoughts, windowDays: 7);

        Assert.Single(context.Thoughts);
        Assert.Equal("test", context.Thoughts[0].Text);
    }
}
