// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services;
using AntarMindAI.Api.Services.Insights;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Tests.Services.Insights;

public class RepetitionDetectorTests
{
    private static RepetitionDetector CreateDetector(double threshold = 0.3) =>
        new(new TextPreprocessor(),
            new ConfigurationBuilder()
                .AddInMemoryCollection(new Dictionary<string, string?>
                {
                    ["PatternDetection:RepetitionSimilarityThreshold"] = threshold.ToString()
                })
                .Build());

    private static ThoughtEntry T(string text) =>
        new() { Id = Guid.NewGuid().ToString(), Text = text, Sentiment = "Neutral", CreatedAt = DateTimeOffset.UtcNow };

    [Fact]
    public void Analyze_ClusterOfThreeSimilarThoughts_ReturnsInsight()
    {
        var detector = CreateDetector();
        var thoughts = new List<ThoughtEntry>
        {
            T("trading stocks today market profit"),
            T("trading stocks market making profit"),
            T("stocks market trading profit today"),
            T("walked the dog in the park")  // unrelated — should not cluster
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = detector.Analyze(context);

        Assert.Contains(insights, i => i.Category == "Repetition" && i.Message.Contains("3 times"));
    }

    [Fact]
    public void Analyze_UnrelatedThoughts_NoInsights()
    {
        var detector = CreateDetector();
        var thoughts = new List<ThoughtEntry>
        {
            T("trading stocks profit"),
            T("mental health meditation yoga"),
            T("learning python machine code"),
            T("family dinner weekend home")
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = detector.Analyze(context);

        Assert.Empty(insights);
    }

    [Fact]
    public void Jaccard_SameTokenSets_ReturnsOne()
    {
        // Verify Jaccard logic indirectly: identical texts → same tokens → similarity = 1.0 → cluster
        var detector = CreateDetector(threshold: 0.9);
        var thoughts = new List<ThoughtEntry>
        {
            T("stressed anxious overwhelmed work deadline"),
            T("stressed anxious overwhelmed work deadline"),
            T("stressed anxious overwhelmed work deadline")
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = detector.Analyze(context);

        Assert.NotEmpty(insights);
    }

    [Fact]
    public void Analyze_FewerThanThreeThoughts_ReturnsNoInsights()
    {
        var detector = CreateDetector();
        var thoughts = new List<ThoughtEntry>
        {
            T("trading stocks"), T("trading stocks")
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = detector.Analyze(context);

        Assert.Empty(insights);
    }
}
