// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services.Insights;

namespace AntarMindAI.Tests.Services.Insights;

public class TimeTrendAnalyzerTests
{
    private static ThoughtEntry NegativeAt(int hour) =>
        new() { Id = Guid.NewGuid().ToString(), Text = "bad day", Sentiment = "Negative",
                CreatedAt = DateTimeOffset.UtcNow.Date.AddHours(hour).ToUniversalTime() };

    private static ThoughtEntry NeutralAt(int hour) =>
        new() { Id = Guid.NewGuid().ToString(), Text = "just a thought", Sentiment = "Neutral",
                CreatedAt = DateTimeOffset.UtcNow.Date.AddHours(hour).ToUniversalTime() };

    [Fact]
    public void Analyze_PeakNegativeWindow_ReturnsTimeTrendInsight()
    {
        // 3 negative thoughts at hours 20, 21, 22 and 0 neutral → 100% negative rate in 20-24 window
        var thoughts = new List<ThoughtEntry>
        {
            NegativeAt(20), NegativeAt(21), NegativeAt(22),
            NeutralAt(8), NeutralAt(9)
        };
        var context = new PatternAnalysisContext(thoughts, 7);
        var analyzer = new TimeTrendAnalyzer();

        var insights = analyzer.Analyze(context);

        Assert.Contains(insights, i => i.Category == "TimeTrend" && i.Message.Contains("peak"));
    }

    [Fact]
    public void Analyze_PeakActivityDay_ReturnsInsight()
    {
        // 4 thoughts on the same day-of-week to trigger peak day insight
        var monday = GetNextWeekday(DayOfWeek.Monday);
        var thoughts = Enumerable.Range(0, 4)
            .Select(_ => new ThoughtEntry { Id = Guid.NewGuid().ToString(), Text = "t", Sentiment = "Neutral",
                                            CreatedAt = monday.AddHours(_.ToString().Length) })
            .Concat(new[] { NeutralAt(10) })
            .ToList();
        var context = new PatternAnalysisContext(thoughts, 7);
        var analyzer = new TimeTrendAnalyzer();

        var insights = analyzer.Analyze(context);

        Assert.Contains(insights, i => i.Message.Contains("most thoughts on"));
    }

    [Fact]
    public void Analyze_SparseData_ReturnsNoInsights()
    {
        // < 5 thoughts → no time trend insights
        var thoughts = new List<ThoughtEntry>
        {
            NeutralAt(10), NeutralAt(11), NeutralAt(12)
        };
        var context = new PatternAnalysisContext(thoughts, 7);
        var analyzer = new TimeTrendAnalyzer();

        var insights = analyzer.Analyze(context);

        Assert.Empty(insights);
    }

    private static DateTimeOffset GetNextWeekday(DayOfWeek day)
    {
        var date = DateTimeOffset.UtcNow.Date;
        while (date.DayOfWeek != day) date = date.AddDays(1);
        return date;
    }
}
