// Generated by AI on 05/04/2026
using AntarMindAI.Api.Models;
using AntarMindAI.Api.Services.Insights;

namespace AntarMindAI.Tests.Services.Insights;

public class TriggerIdentifierTests
{
    private static ThoughtEntry T(string[] tags, string sentiment) =>
        new() { Id = Guid.NewGuid().ToString(), Text = "test", Tags = tags, Sentiment = sentiment, CreatedAt = DateTimeOffset.UtcNow };

    [Fact]
    public void Analyze_TagWithHighNegativeRate_ReturnsTriggerInsight()
    {
        var identifier = new TriggerIdentifier();
        // 3 negative Work thoughts out of 3 = 100% negative rate
        var thoughts = new List<ThoughtEntry>
        {
            T(["Work"], "Negative"), T(["Work"], "Negative"), T(["Work"], "Negative")
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = identifier.Analyze(context);

        Assert.Contains(insights, i => i.Category == "Trigger" && i.Message.Contains("Work"));
    }

    [Fact]
    public void Analyze_StressCoOccurrence_ReturnsCoInsight()
    {
        var identifier = new TriggerIdentifier();
        // 3 thoughts tagged both Stress+Work → Work co-occurs with Stress 100% of the time
        var thoughts = new List<ThoughtEntry>
        {
            T(["Stress", "Work"], "Negative"),
            T(["Stress", "Work"], "Negative"),
            T(["Stress", "Work"], "Negative")
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = identifier.Analyze(context);

        Assert.Contains(insights, i => i.Message.Contains("Work") && i.Message.Contains("stress"));
    }

    [Fact]
    public void Analyze_TagBelowNegativeThreshold_NoTriggerInsight()
    {
        var identifier = new TriggerIdentifier();
        // 1 negative out of 4 = 25% — below 50% threshold
        var thoughts = new List<ThoughtEntry>
        {
            T(["Trading"], "Negative"),
            T(["Trading"], "Positive"), T(["Trading"], "Positive"), T(["Trading"], "Neutral")
        };
        var context = new PatternAnalysisContext(thoughts, 7);

        var insights = identifier.Analyze(context);

        Assert.DoesNotContain(insights, i => i.Category == "Trigger" && i.Message.Contains("Trading"));
    }

    [Fact]
    public void Analyze_EmptyThoughts_ReturnsNoInsights()
    {
        var identifier = new TriggerIdentifier();
        var context = new PatternAnalysisContext([], 7);

        var insights = identifier.Analyze(context);

        Assert.Empty(insights);
    }
}
