// Generated by AI on 05/04/2026
using AntarMindAI.Api.Repositories;
using AntarMindAI.Api.Services;
using AntarMindAI.Api.Services.Insights;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Api.Controllers.Insights;

[ApiController]
[Authorize]
[Route("api/insights")]
public class InsightsController : ControllerBase
{
    private readonly IInsightService _insightService;
    private readonly ICurrentUserService _currentUserService;
    private readonly IThoughtRepository _repository;
    private readonly int _windowDays;

    public InsightsController(
        IInsightService insightService,
        ICurrentUserService currentUserService,
        IThoughtRepository repository,
        IConfiguration configuration)
    {
        _insightService = insightService;
        _currentUserService = currentUserService;
        _repository = repository;
        _windowDays = configuration.GetValue("PatternDetection:FrequencyWindowDays", 7);
    }

    [HttpGet]
    public async Task<IActionResult> GetInsightsAsync()
    {
        Response.Headers.CacheControl = "no-store";

        var userId = _currentUserService.GetUserId() ?? "anonymous";
        var insights = await _insightService.GetInsightsAsync(userId);
        var allThoughts = await _repository.GetAllByUserAsync(userId);

        var response = new InsightsResponse(
            Insights: insights.Select(i => new InsightMessageResponse(i.Category, i.Message, i.Confidence, i.GeneratedAt)).ToList(),
            ThoughtCount: allThoughts.Count,
            AnalysisWindowDays: _windowDays);

        return Ok(response);
    }
}
