// Generated by AI on 05/04/2026
namespace AntarMindAI.Api.Controllers.Insights;

public record InsightMessageResponse(
    string Category,
    string Message,
    double Confidence,
    DateTimeOffset GeneratedAt);

public record InsightsResponse(
    IReadOnlyList<InsightMessageResponse> Insights,
    int ThoughtCount,
    int AnalysisWindowDays);
