// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services;
using AntarMindAI.Api.Services.Insights;
using AntarMindAI.Api.Services.Reflections;

namespace AntarMindAI.Tests.Services;

public class AiSummaryServiceTests
{
    private static WeeklyReflection EmptyReflection() => new(
        WeekStart: DateTimeOffset.UtcNow,
        WeekEnd: DateTimeOffset.UtcNow.AddDays(6),
        TotalThoughts: 0,
        CategoryDistribution: [],
        DailySentimentTrend: [],
        PeakActivityByHour: [],
        TopInsights: [],
        AiSummary: null);

    [Fact]
    public async Task NullAiSummaryService_AlwaysReturnsNull()
    {
        var svc = new NullAiSummaryService();

        var result = await svc.GenerateWeeklySummaryAsync(EmptyReflection());

        Assert.Null(result);
    }

    [Fact]
    public async Task OpenAiSummaryService_OnException_ReturnsNull()
    {
        // Empty API key will cause request to fail; service must catch and return null
        var svc = new OpenAiSummaryService(apiKey: "invalid-key-for-test");

        var result = await svc.GenerateWeeklySummaryAsync(EmptyReflection());

        Assert.Null(result);
    }
}
