// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services.Embeddings;

namespace AntarMindAI.Tests.Services;

public class EmbeddingServiceTests
{
    [Fact]
    public async Task NullEmbeddingService_GetEmbeddingAsync_ReturnsEmptyArray()
    {
        var svc = new NullEmbeddingService();
        var result = await svc.GetEmbeddingAsync("hello world");
        Assert.Empty(result);
    }

    [Fact]
    public async Task NullEmbeddingService_FindSimilarAsync_ReturnsEmptyList()
    {
        var svc = new NullEmbeddingService();
        var result = await svc.FindSimilarAsync("user1", "thought-id");
        Assert.Empty(result);
    }
}
