// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Tests.Services;

public class RuleBasedSentimentAnalyzerTests
{
    private static RuleBasedSentimentAnalyzer CreateAnalyzer() =>
        new(new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["SentimentAnalyzer:PositiveKeywords:great"] = "0.8",
                ["SentimentAnalyzer:PositiveKeywords:good"] = "0.6",
                ["SentimentAnalyzer:PositiveKeywords:happy"] = "0.8",
                ["SentimentAnalyzer:PositiveKeywords:profit"] = "0.6",
                ["SentimentAnalyzer:PositiveKeywords:excellent"] = "0.9",
                ["SentimentAnalyzer:NegativeKeywords:bad"] = "0.6",
                ["SentimentAnalyzer:NegativeKeywords:terrible"] = "0.9",
                ["SentimentAnalyzer:NegativeKeywords:sad"] = "0.7",
                ["SentimentAnalyzer:NegativeKeywords:loss"] = "0.6",
                ["SentimentAnalyzer:NegativeKeywords:stressed"] = "0.7",
            })
            .Build());

    [Fact]
    public void Analyze_PositiveTokens_ReturnsPositiveSentiment()
    {
        var analyzer = CreateAnalyzer();

        var result = analyzer.Analyze(["great", "day", "trading"]);

        Assert.Equal("Positive", result.Sentiment);
    }

    [Fact]
    public void Analyze_NegativeTokens_ReturnsNegativeSentiment()
    {
        var analyzer = CreateAnalyzer();

        var result = analyzer.Analyze(["terrible", "loss", "sad"]);

        Assert.Equal("Negative", result.Sentiment);
    }

    [Fact]
    public void Analyze_NeutralTokens_ReturnsNeutralSentiment()
    {
        var analyzer = CreateAnalyzer();

        var result = analyzer.Analyze(["market", "today", "reading"]);

        Assert.Equal("Neutral", result.Sentiment);
    }

    [Fact]
    public void Analyze_IntensityScore_IsBetweenZeroAndOne()
    {
        var analyzer = CreateAnalyzer();

        var result = analyzer.Analyze(["excellent", "profit", "happy", "great"]);

        Assert.InRange(result.IntensityScore, 0.0, 1.0);
    }

    [Fact]
    public void Analyze_HighIntensityPositive_HasHighScore()
    {
        var analyzer = CreateAnalyzer();

        var result = analyzer.Analyze(["excellent", "great", "happy"]);

        Assert.Equal("Positive", result.Sentiment);
        Assert.True(result.IntensityScore > 0.1);
    }

    [Fact]
    public void Analyze_EmptyTokens_ReturnsNeutralWithZeroIntensity()
    {
        var analyzer = CreateAnalyzer();

        var result = analyzer.Analyze([]);

        Assert.Equal("Neutral", result.Sentiment);
        Assert.Equal(0.0, result.IntensityScore);
    }

    [Fact]
    public void Analyze_MixedTokens_ScoreReflectsNetBalance()
    {
        var analyzer = CreateAnalyzer();

        // great (0.8) - terrible (0.9) = -0.1 → Neutral (barely)
        var result = analyzer.Analyze(["great", "terrible"]);

        Assert.Equal("Neutral", result.Sentiment);
    }

    [Fact]
    public void Analyze_NotBad_FlipsToPositive()
    {
        var analyzer = CreateAnalyzer();

        // "not" negates "bad" → score = +0.6 → Positive
        var result = analyzer.Analyze(["not", "bad"]);

        Assert.Equal("Positive", result.Sentiment);
    }

    [Fact]
    public void Analyze_NotGood_FlipsToNegative()
    {
        var analyzer = CreateAnalyzer();

        // "not" negates "good" → score = -0.6 → Negative
        var result = analyzer.Analyze(["not", "good"]);

        Assert.Equal("Negative", result.Sentiment);
    }

    [Fact]
    public void Analyze_NegationWindowExpires_AfterThreeTokens()
    {
        var analyzer = CreateAnalyzer();

        // "not" + 3 neutral tokens + "great" → negation window expired → Positive
        var result = analyzer.Analyze(["not", "aa", "bb", "cc", "great"]);

        Assert.Equal("Positive", result.Sentiment);
    }

    [Fact]
    public void Analyze_IntensityScore_UsesNonLinearCurve()
    {
        var analyzer = CreateAnalyzer();

        // Single "great" (0.8): sigmoid(0.8) ≈ 0.66 which is less than linear min(1, 0.8)=0.8
        var result = analyzer.Analyze(["great"]);

        Assert.InRange(result.IntensityScore, 0.0, 1.0);
        Assert.True(result.IntensityScore < 0.9); // sigmoid keeps it below linear clamp
    }
}
