// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Tests.Services;

public class RuleBasedTaggingEngineTests
{
    private static RuleBasedTaggingEngine CreateEngine() =>
        new(new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["TaggingEngine:Keywords:Trading:0"] = "trade",
                ["TaggingEngine:Keywords:Trading:1"] = "trading",
                ["TaggingEngine:Keywords:Trading:2"] = "stock",
                ["TaggingEngine:Keywords:Trading:3"] = "portfolio",
                ["TaggingEngine:Keywords:Trading:4"] = "profit",
                ["TaggingEngine:Keywords:Work:0"] = "work",
                ["TaggingEngine:Keywords:Work:1"] = "meeting",
                ["TaggingEngine:Keywords:Work:2"] = "deadline",
                ["TaggingEngine:Keywords:Work:3"] = "project",
                ["TaggingEngine:Keywords:Work:4"] = "manager",
                ["TaggingEngine:Keywords:Health:0"] = "exercise",
                ["TaggingEngine:Keywords:Health:1"] = "sleep",
                ["TaggingEngine:Keywords:Health:2"] = "gym",
                ["TaggingEngine:Keywords:Health:3"] = "diet",
                ["TaggingEngine:Keywords:Health:4"] = "pain",
                ["TaggingEngine:Keywords:Stress:0"] = "stress",
                ["TaggingEngine:Keywords:Stress:1"] = "anxious",
                ["TaggingEngine:Keywords:Stress:2"] = "overwhelmed",
                ["TaggingEngine:Keywords:Ideas:0"] = "idea",
                ["TaggingEngine:Keywords:Ideas:1"] = "build",
                ["TaggingEngine:Keywords:Ideas:2"] = "design",
            })
            .Build());

    [Fact]
    public void GetTags_TradingTokens_ReturnsTradingTag()
    {
        var engine = CreateEngine();

        var tags = engine.GetTags(["trading", "portfolio", "today"]);

        Assert.Contains("Trading", tags);
    }

    [Fact]
    public void GetTags_WorkTokens_ReturnsWorkTag()
    {
        var engine = CreateEngine();

        var tags = engine.GetTags(["meeting", "deadline", "finished"]);

        Assert.Contains("Work", tags);
    }

    [Fact]
    public void GetTags_HealthTokens_ReturnsHealthTag()
    {
        var engine = CreateEngine();

        var tags = engine.GetTags(["gym", "exercise", "morning"]);

        Assert.Contains("Health", tags);
    }

    [Fact]
    public void GetTags_MultiDomainTokens_ReturnsMultipleTags()
    {
        var engine = CreateEngine();

        // "project" → Work, "stress" → Stress
        var tags = engine.GetTags(["project", "stress", "deadline"]);

        Assert.Contains("Work", tags);
        Assert.Contains("Stress", tags);
    }

    [Fact]
    public void GetTags_BigramMatch_ReturnsDomainTag()
    {
        var engine = new RuleBasedTaggingEngine(
            new ConfigurationBuilder()
                .AddInMemoryCollection(new Dictionary<string, string?>
                {
                    ["TaggingEngine:Bigrams:Work:0"] = "pull request",
                    ["TaggingEngine:Bigrams:Learning:0"] = "machine learning",
                })
                .Build());

        var workTags = engine.GetTags(["pull", "request", "merged"]);
        var learningTags = engine.GetTags(["studying", "machine", "learning", "today"]);

        Assert.Contains("Work", workTags);
        Assert.Contains("Learning", learningTags);
    }

    [Fact]
    public void GetTags_UnrelatedTokens_ReturnsEmptyList()
    {
        var engine = CreateEngine();

        var tags = engine.GetTags(["pizza", "sunshine", "walking"]);

        Assert.Empty(tags);
    }

    [Fact]
    public void GetTags_EmptyTokens_ReturnsEmptyList()
    {
        var engine = CreateEngine();

        var tags = engine.GetTags([]);

        Assert.Empty(tags);
    }

    [Fact]
    public void GetTags_IsCaseInsensitive()
    {
        var engine = CreateEngine();

        var tags = engine.GetTags(["TRADING", "STOCK"]);

        Assert.Contains("Trading", tags);
    }
}
