// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services;

namespace AntarMindAI.Tests.Services;

public class TextPreprocessorTests
{
    private readonly TextPreprocessor _preprocessor = new();

    [Fact]
    public void Tokenize_MixedCaseText_ReturnsLowercase()
    {
        var tokens = _preprocessor.Tokenize("Hello WORLD Today");

        Assert.All(tokens, t => Assert.Equal(t, t.ToLowerInvariant()));
    }

    [Fact]
    public void Tokenize_PunctuationText_RemovesPunctuation()
    {
        var tokens = _preprocessor.Tokenize("trading, stocks! markets?");

        Assert.DoesNotContain(",", tokens);
        Assert.DoesNotContain("!", tokens);
        Assert.DoesNotContain("?", tokens);
        Assert.Contains("trading", tokens);
        Assert.Contains("stocks", tokens);
        Assert.Contains("markets", tokens);
    }

    [Fact]
    public void Tokenize_StopWords_AreFiltered()
    {
        var tokens = _preprocessor.Tokenize("the market is doing well today");

        Assert.DoesNotContain("the", tokens);
        Assert.DoesNotContain("is", tokens);
        Assert.Contains("market", tokens);
        Assert.Contains("doing", tokens);
        Assert.Contains("well", tokens);
    }

    [Fact]
    public void Tokenize_EmptyString_ReturnsEmptyList()
    {
        var tokens = _preprocessor.Tokenize(string.Empty);

        Assert.Empty(tokens);
    }

    [Fact]
    public void Tokenize_WhitespaceOnly_ReturnsEmptyList()
    {
        var tokens = _preprocessor.Tokenize("   ");

        Assert.Empty(tokens);
    }

    [Fact]
    public void Tokenize_SingleCharTokens_AreFiltered()
    {
        var tokens = _preprocessor.Tokenize("I a b c go read");

        Assert.DoesNotContain("a", tokens);
        Assert.DoesNotContain("b", tokens);
        Assert.DoesNotContain("c", tokens);
        Assert.Contains("read", tokens);
    }

    [Fact]
    public void Tokenize_MultipleSpaces_HandledGracefully()
    {
        var tokens = _preprocessor.Tokenize("trading   stocks   market");

        Assert.Contains("trading", tokens);
        Assert.Contains("stocks", tokens);
        Assert.Contains("market", tokens);
    }
}
