// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services;
using Microsoft.Extensions.Configuration;

namespace AntarMindAI.Tests.Services;

public class ThoughtAnalysisPipelineTests
{
    private static ThoughtAnalysisPipeline CreatePipeline()
    {
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["TaggingEngine:Keywords:Trading:0"] = "trade",
                ["TaggingEngine:Keywords:Trading:1"] = "stock",
                ["TaggingEngine:Keywords:Trading:2"] = "portfolio",
                ["TaggingEngine:Keywords:Work:0"] = "meeting",
                ["TaggingEngine:Keywords:Work:1"] = "deadline",
                ["TaggingEngine:Keywords:Stress:0"] = "stressed",
                ["TaggingEngine:Keywords:Stress:1"] = "overwhelmed",
                ["SentimentAnalyzer:PositiveKeywords:great"] = "0.8",
                ["SentimentAnalyzer:PositiveKeywords:profit"] = "0.6",
                ["SentimentAnalyzer:NegativeKeywords:loss"] = "0.6",
                ["SentimentAnalyzer:NegativeKeywords:terrible"] = "0.9",
            })
            .Build();

        return new ThoughtAnalysisPipeline(
            new TextPreprocessor(),
            new RuleBasedTaggingEngine(config),
            new RuleBasedSentimentAnalyzer(config));
    }

    [Fact]
    public void Analyze_TradingText_ReturnsCorrectTags()
    {
        var pipeline = CreatePipeline();

        var result = pipeline.Analyze("My stock portfolio had a great day today.");

        Assert.Contains("Trading", result.Tags);
    }

    [Fact]
    public void Analyze_PositiveText_ReturnsPositiveSentiment()
    {
        var pipeline = CreatePipeline();

        var result = pipeline.Analyze("Great profit on my trades today.");

        Assert.Equal("Positive", result.Sentiment);
    }

    [Fact]
    public void Analyze_NegativeText_ReturnsNegativeSentiment()
    {
        var pipeline = CreatePipeline();

        var result = pipeline.Analyze("Terrible loss on my stock portfolio.");

        Assert.Equal("Negative", result.Sentiment);
    }

    [Fact]
    public void Analyze_MultiDomainText_ReturnsMultipleTags()
    {
        var pipeline = CreatePipeline();

        var result = pipeline.Analyze("I have a deadline meeting and I'm stressed about it.");

        Assert.Contains("Work", result.Tags);
        Assert.Contains("Stress", result.Tags);
    }

    [Fact]
    public void Analyze_IntensityScore_IsBetweenZeroAndOne()
    {
        var pipeline = CreatePipeline();

        var result = pipeline.Analyze("Great profit today on my portfolio.");

        Assert.InRange(result.IntensityScore, 0.0, 1.0);
    }

    [Fact]
    public void Analyze_EmptyText_ReturnsDefaults()
    {
        var pipeline = CreatePipeline();

        var result = pipeline.Analyze(string.Empty);

        Assert.Empty(result.Tags);
        Assert.Equal("Neutral", result.Sentiment);
        Assert.Equal(0.0, result.IntensityScore);
    }
}
