// Generated by AI on 05/04/2026
using AntarMindAI.Api.Repositories;
using Microsoft.Extensions.DependencyInjection;

namespace AntarMindAI.Tests.Repositories;

public class RepositorySelectionTests : IClassFixture<TestApiFactory>
{
    private readonly TestApiFactory _factory;

    public RepositorySelectionTests(TestApiFactory factory)
    {
        _factory = factory;
    }

    [Fact]
    public void WhenNoConnectionString_UsesInMemoryThoughtRepository()
    {
        // TestApiFactory runs in "Testing" environment with no Azure connection string
        using var scope = _factory.Services.CreateScope();
        var repository = scope.ServiceProvider.GetRequiredService<IThoughtRepository>();

        Assert.IsType<InMemoryThoughtRepository>(repository);
    }
}
