// Generated by AI on 05/04/2026
using System.Net;
using System.Net.Http.Json;

namespace AntarMindAI.Tests.Export;

public class ExportControllerTests : IClassFixture<TestApiFactory>
{
    private readonly HttpClient _client;

    public ExportControllerTests(TestApiFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task ExportCsv_ReturnsCorrectContentType()
    {
        var response = await _client.GetAsync("/api/export?format=csv");
        response.EnsureSuccessStatusCode();

        Assert.Equal("text/csv", response.Content.Headers.ContentType?.MediaType);
    }

    [Fact]
    public async Task ExportCsv_ContainsCsvHeaders()
    {
        var response = await _client.GetAsync("/api/export?format=csv");
        var body = await response.Content.ReadAsStringAsync();

        Assert.Contains("Id,Text,CreatedAt,Tags,Sentiment,IntensityScore", body);
    }

    [Fact]
    public async Task ExportCsv_ContentDispositionContainsFilename()
    {
        var response = await _client.GetAsync("/api/export?format=csv");

        var cd = response.Content.Headers.ContentDisposition?.ToString() ?? string.Empty;
        Assert.Contains("thoughts-export-", cd);
        Assert.Contains(".csv", cd);
    }

    [Fact]
    public async Task ExportJson_ReturnsJsonArray()
    {
        var response = await _client.GetAsync("/api/export?format=json");
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadAsStringAsync();
        // Should be a JSON array (empty or populated)
        Assert.True(body.TrimStart().StartsWith('[') || body.TrimStart().StartsWith('{'));
    }

    [Fact]
    public async Task ExportUnknownFormat_Returns400()
    {
        var response = await _client.GetAsync("/api/export?format=xml");

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
    }
}
