// Generated by AI on 05/04/2026
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import { InsightsPanel } from '../components/InsightsPanel';

export function InsightsPage() {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Typography variant="h4" component="h1" gutterBottom>
        Insights
      </Typography>
      <InsightsPanel />
    </Container>
  );
}
