// Generated by AI on 05/04/2026
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export function LandingPage() {
  return (
    <Box sx={{ p: 4, textAlign: 'center' }}>
      <Typography variant="h3" gutterBottom>
        Welcome to AntarMindAI
      </Typography>
      <Typography variant="body1" color="text.secondary">
        Your AI-powered platform. Get started by exploring the features above.
      </Typography>
    </Box>
  );
}
