// Generated by AI on 05/04/2026
import { Route, Routes } from 'react-router-dom';
import { AppHeader } from './components/AppHeader';
import { LandingPage } from './pages/LandingPage';

function App() {
  return (
    <>
      <AppHeader />
      <Routes>
        <Route path="/" element={<LandingPage />} />
      </Routes>
    </>
  );
}

export default App;
