// Generated by AI on 05/04/2026
namespace AntarMindAI.Tests.Health;

public class HealthControllerTests : IClassFixture<TestApiFactory>
{
    private readonly HttpClient _client;

    public HealthControllerTests(TestApiFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task GetHealth_ReturnsOkWithStatusOk()
    {
        var response = await _client.GetAsync("/api/health");

        response.EnsureSuccessStatusCode();
        var content = await response.Content.ReadAsStringAsync();
        Assert.Contains("ok", content);
    }
}
