// Generated by AI on 05/04/2026
using AntarMindAI.Api.Services;
using AntarMindAI.Api.Services.Reflections;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AntarMindAI.Api.Controllers.Reflections;

[ApiController]
[Authorize]
[Route("api/reflections")]
public class ReflectionsController : ControllerBase
{
    private readonly IWeeklyReflectionService _reflectionService;
    private readonly ICurrentUserService _currentUserService;

    public ReflectionsController(
        IWeeklyReflectionService reflectionService,
        ICurrentUserService currentUserService)
    {
        _reflectionService = reflectionService;
        _currentUserService = currentUserService;
    }

    [HttpGet("weekly")]
    public async Task<IActionResult> GetWeeklyReflectionAsync([FromQuery] string? weekDate = null)
    {
        DateTimeOffset? parsedDate = null;

        if (weekDate is not null)
        {
            if (!DateTimeOffset.TryParse(weekDate, out var parsed))
            {
                return BadRequest(new
                {
                    correlationId = HttpContext.TraceIdentifier,
                    status = 400,
                    title = "Invalid date format",
                    detail = "weekDate must be a valid ISO 8601 date (e.g. 2026-05-04).",
                    source = "weekDate"
                });
            }
            parsedDate = parsed;
        }

        var userId = _currentUserService.GetUserId() ?? "anonymous";
        var reflection = await _reflectionService.GetWeeklyReflectionAsync(userId, parsedDate);

        var response = new WeeklyReflectionResponse(
            WeekStart: reflection.WeekStart,
            WeekEnd: reflection.WeekEnd,
            TotalThoughts: reflection.TotalThoughts,
            CategoryDistribution: reflection.CategoryDistribution
                .Select(c => new CategoryCountResponse(c.Category, c.Count, c.Percentage)).ToList(),
            DailySentimentTrend: reflection.DailySentimentTrend
                .Select(d => new DailySentimentResponse(d.Day.ToString(), d.Positive, d.Negative, d.Neutral)).ToList(),
            PeakActivityByHour: reflection.PeakActivityByHour
                .Select(h => new HourlyActivityResponse(h.Hour, h.ThoughtCount)).ToList(),
            TopInsights: reflection.TopInsights
                .Select(i => new InsightMessageResponse(i.Category, i.Message, i.Confidence)).ToList(),
            AiSummary: reflection.AiSummary);

        return Ok(response);
    }
}
