// Generated by AI on 05/04/2026
using System.Net;
using System.Text.Json;

namespace AntarMindAI.Tests.Insights;

public class InsightsControllerTests : IClassFixture<TestApiFactory>
{
    private readonly HttpClient _client;
    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    public InsightsControllerTests(TestApiFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task GetInsights_Authenticated_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/insights");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetInsights_ReturnsNoCacheHeader()
    {
        var response = await _client.GetAsync("/api/insights");

        Assert.Equal("no-store", response.Headers.CacheControl?.ToString());
    }

    [Fact]
    public async Task GetInsights_FewThoughts_ReturnsEmptyInsights()
    {
        // Testing env uses in-memory storage with zero thoughts seeded → below MinimumThoughtsForInsights
        var response = await _client.GetAsync("/api/insights");
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);
        var insights = doc.RootElement.GetProperty("insights");

        Assert.Equal(JsonValueKind.Array, insights.ValueKind);
        Assert.Equal(0, insights.GetArrayLength());
    }

    [Fact]
    public async Task GetInsights_ResponseContainsThoughtCountAndWindowDays()
    {
        var response = await _client.GetAsync("/api/insights");
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);

        Assert.True(doc.RootElement.TryGetProperty("thoughtCount", out _));
        Assert.True(doc.RootElement.TryGetProperty("analysisWindowDays", out _));
    }
}
