// Generated by AI on 05/04/2026
using System.Net;
using System.Text.Json;

namespace AntarMindAI.Tests.Reflections;

public class ReflectionsControllerTests : IClassFixture<TestApiFactory>
{
    private readonly HttpClient _client;

    public ReflectionsControllerTests(TestApiFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task GetWeeklyReflection_NoDateParam_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reflections/weekly");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetWeeklyReflection_ValidDateParam_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reflections/weekly?weekDate=2026-05-04");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetWeeklyReflection_InvalidDateParam_Returns400()
    {
        var response = await _client.GetAsync("/api/reflections/weekly?weekDate=not-a-date");

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
    }

    [Fact]
    public async Task GetWeeklyReflection_ResponseContainsRequiredFields()
    {
        var response = await _client.GetAsync("/api/reflections/weekly");
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);

        Assert.True(doc.RootElement.TryGetProperty("weekStart", out _));
        Assert.True(doc.RootElement.TryGetProperty("weekEnd", out _));
        Assert.True(doc.RootElement.TryGetProperty("totalThoughts", out _));
        Assert.True(doc.RootElement.TryGetProperty("categoryDistribution", out _));
        Assert.True(doc.RootElement.TryGetProperty("dailySentimentTrend", out var dsTrend));
        Assert.Equal(7, dsTrend.GetArrayLength());
        Assert.True(doc.RootElement.TryGetProperty("peakActivityByHour", out var hourly));
        Assert.Equal(24, hourly.GetArrayLength());
    }

    [Fact]
    public async Task GetWeeklyReflection_NoThoughts_ReturnsTotalZero()
    {
        var response = await _client.GetAsync("/api/reflections/weekly");
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);

        Assert.Equal(0, doc.RootElement.GetProperty("totalThoughts").GetInt32());
    }
}
